### ISSUE TITLE
deploy MetaCell/nwb-explorer and link to dandiarchive

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-infrastructure#10]
Provides a nice interactive browser, see https://github.com/MetaCell/nwb-explorer/issues/117#issuecomment-546057480

From https://github.com/MetaCell/nwb-explorer#getting-started-with-nwb-explorer it looks like it should be trivial to get it used from dandiarchive.org.  
We could try to make it work from some dedicated instance to start with and then see if we could fire up a dedicated to user (and possibly paid by them) instance via mybinder or other (terra?) setup.

Aspects to address
- authentication (like there is one via github for current dandi's jupyter hub instance)

attn @satra  @mgrauer

**Comment by pgleeson** [comment]
FYI the live instance of NWB Explorer at Open Source Brain can be used for viewing (some, <100MB) NWB files using links constructed like:
http://nwbexplorer.opensourcebrain.org/nwbfile=https://girder.dandiarchive.org/api/v1/item/5eaa26251fe11561ec13ea18/download

Can discuss this and future plans for caching etc. at the NWB hackathon next week.

**Comment by satra** [comment]
thanks @pgleeson - yes, let's chat next week.

**Comment by yarikoptic** [comment]
note: FWIW, metacell issue was fixed.

**Comment by yarikoptic** [comment]
we have added integration https://github.com/dandi/dandi-archive/blob/2c86402dbdd3633ec1cd7d67926dc2fbd62a35f7/web/src/views/FileBrowserView/FileBrowser.vue#L253
