### ISSUE TITLE
Use policy for log buckets instead of ACL

### ISSUE THREAD

**Issue by dchiquito** [dandi/dandi-infrastructure#108]
IMO (and possibly AWS's opinion), policies are generally easier to manage than ACLs.

The docs also recommend that you use a policy, rather than ACLs, to enable log delivery: https://docs.aws.amazon.com/AmazonS3/latest/userguide/enable-server-access-logging.html

_Originally posted by @brianhelba in https://github.com/dandi/dandi-infrastructure/pull/105#discussion_r774092634_

**Comment by danlamanna** [comment]
Duplicated by #137
