### ISSUE TITLE
Investigate if we need ACLs enabled on S3 buckets

### ISSUE THREAD

**Issue by dchiquito** [dandi/dandi-infrastructure#114]
For all our S3 buckets, we have this Object Ownership setting:
![image](https://user-images.githubusercontent.com/577946/152254068-5b3bc17c-ad62-4cc3-ac22-ed59863efb67.png)

In all of our permission policies, we require that `x-amz-acl` be set to `bucket-owner-full-control`. This seems to have the net effect of disabling ACLs, but also requiring that clients set a header on any write request (and also making our policies more complex). I don't see any reason not to simply disable ACLs, but perhaps there is something I'm not thinking of.

@brianhelba ?

(CC @AlmightyYakob )

**Comment by danlamanna** [comment]
Duplicated by https://github.com/dandi/dandi-infrastructure/issues/137
