### ISSUE TITLE
Use AWS for SMTP

### ISSUE THREAD

**Issue by brianhelba** [dandi/dandi-infrastructure#14]
Mailgun no longer provides a free plan, and is a larger non-shareable infrastructure surface.

* Provision AWS resources
* Update Girder settings
* Determine if any other services use Mailgun
* Contact @mgrauer to delete Mailgun domain

**Comment by yarikoptic** [comment]
@waxlamp - could this be closed ? (ideally with some reference or detail on current mail setup)

**Comment by yarikoptic** [comment]
reopen if still pertinent

**Comment by waxlamp** [comment]
This is solved--we are using ImprovMX for handling incoming mail, and AWS is used to send outgoing mail.
