### ISSUE TITLE
embargo via encryption

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-infrastructure#16]
A possibly stupid idea came up to me while discussing aspect of embargo.
If it is possible to encrypt data and/or metadata within hdf5 files without major impact on IO later, we could potentially provide "embargo" support by simply allowing to upload files with encrypted content.  Then data owners could share the keys (and with us privately before upload) with people whom they want to "share" the data.

**Comment by satra** [comment]
@yarikoptic - i like this idea a lot.

**Comment by satra** [comment]
we would have to decide if exposing metadata of items is ok during embargo.

**Comment by yarikoptic** [comment]
probably a no go since would be HDF5/NWB specific.  So I will just let it RiP

**Comment by waxlamp** [comment]
My own thinking was to simply encrypt the bytes, rather than doing it in-band for HDF or any other specific file type. If "delisting" from the app is enough obfuscation for embargo, then that's a good reason not to think about encryption for this purpose.

**Comment by waxlamp** [comment]
BTW this issue should not be in the dandi-infrastructure repo. Perhaps we can move this to helpdesk or dandi-api?

**Comment by yarikoptic** [comment]
FWIW it was filed here before we had any of those other venues such as a helpdesk.  Also I feel that helpdesk is more of a "user-oriented" not for us to discuss design. I guess we have diluted it by now ;)

As for "bytes encryption" file-format agnostic -- would prevent ROS3 (or probably any other httpfs-like usage), would likely require decryption upon dandiset going "open", etc.
