### ISSUE TITLE
Manage public bucket via terraform?

### ISSUE THREAD

**Issue by mgrauer** [dandi/dandi-infrastructure#34]
@satra @yarikoptic

There is the AWS public bucket where we will put our production assets. Most of our production infrastructure for the API is managed by Terraform. This question is asking whether we want to put the AWS public bucket under Terraform management--if we do put it under Terraform, then we cannot be making any changes to the bucket via the AWS console or any route other than Terraform, including permissions and policies. Terraform has the advantage that all of the changes will be tracked and audited, and the bucket will always be in a known state.

Either way, we need to know the answer to this question so we can plot a path forward for moving the API to the public bucket.

What do you think? 

/cc @waxlamp @brianhelba @dchiquito

**Comment by satra** [comment]
AWS has control over that bucket since it is a public bucket they provide. you cannot set policies on it that deviate from AWS policies for a public bucket. 

I think easiest for the moment (without understanding the changes that terraform would want to make) one is to create a prefix in the bucket (as @yarikoptic mentioned in the asset PR) that the API server is allowed to write to. 

we will also likely want to control policies for specific prefixes so we can potentially handout aws tokens for large uploads (potentially out of sync with the API server and CLI). also we may want to adjust policies to mount this bucket via FSx for dandihub, etc.,.

do you have a notion of what policies terraform would want to control?

**Comment by mgrauer** [comment]
With Terraform we would set whatever policies we want on the bucket, it is more about what is the source of truth (terraform vs the console). It won't work to split policies across Terraform and the console, so we have to be all in for Terraform if we are going to use it to set policies.

Said another way, you can set whatever policies you want via Terraform, but you should set *all* via Terraform, regardless of prefix. We wouldn't want to set any policies that deviate from what AWS require of us.

I believe we can set all of the policies that you want via Terraform, for whatever prefixes you want. If we go with Terraform, it means that everyone who wants to set a policy on the bucket needs to do it through Terraform.

**Comment by mgrauer** [comment]
Capturing some slack chat with @satra:

Satra:

> The overall policies (e.g., public access) are set by AWS and they can change them at any point. are you saying you want to recreate the bucket and reset policies to match the aws policies? i'm pretty sure you cannot do that.  we are asked not to change any policies on that bucket. however we can potentially adjust policies on sub prefixes of that bucket. for our current use of dandiarchive with girder, we have an external account (our dandi account) that has a policy associated with it that allows it to write.

Mike:

> we don't need to recreate the bucket, but we could match the existing policies or leave them alone, and then change sub policies. i'm thinking overall it might be better to leave this one out of terraform, because of the complexity and probably some unknowns of how AWS has set up and maintains ownership over the bucket.

Satra:

> we will still need to figure out how the api server will talk to that bucket. in aws, girder is authorized at an account level. we don't use access key/secret for that but a policy. but since the api server is running on heroku, we will probably need to mint something else for it.

**Comment by waxlamp** [comment]
Working out prerequisites for answering this question in dandi/dandi-api#149.

**Comment by brianhelba** [comment]
With #38, the "public bucket" (which I've started calling the "sponsored bucket") is now manged under Terraform: https://github.com/dandi/dandi-infrastructure/blob/master/terraform/sponsored_bucket.tf

The bucket configuration was not changed as a result of adding to Terraform; it's just now documented in a rigorous way. This is an essential sanity measure to understand the current configuration and to update the overall configuration to properly support cross-account access.

Once this process is complete, we may be able to determine that it's possible to drop the bucket itself from Terraform management, if we decide that's desired.
