### ISSUE TITLE
Create an EC2 Celery worker

### ISSUE THREAD

**Issue by waxlamp** [dandi/dandi-infrastructure#35]
Celery currently runs in Heroku; we want to move that to EC2.

**Comment by satra** [comment]
i'm just noting the following, which are optimizations rather than blockers. consider Amazon FSx to mount the s3 bucket for rapid access. also consider whether AWS batch could be used to run the workers.

**Comment by yarikoptic** [comment]
@waxlamp @satra: what would be the purpose/motivation? (e.g. better speeds since data is in AWS)

**Comment by satra** [comment]
no egress costs and potentially better speeds, but not high priority.

**Comment by waxlamp** [comment]
We would be incurring costs for running EC2 instead, right? Currently we don't pay egress costs against the sponsored bucket anyway.

Since this would cost a lot of engineering time plus uncertainty, compared to a solution that is working for us now, I'd argue to close this unless and until we have a clear need to shift our stack for workers.

**Comment by satra** [comment]
we can close this issue for now, and revisit when we augment the task manager to run pipelines. at that point, we may want to run those all on ec2.
