### ISSUE TITLE
Remove "chiquito-tfdemo" resources/reassign his issues

### ISSUE THREAD

**Issue by brianhelba** [dandi/dandi-infrastructure#40]
There are a number of IAM resources labeled `chiquito-tfdemo` (or similar). If these are no longer necessary, they should be destroyed.

**Comment by yarikoptic** [comment]
@waxlamp please check if anything still to be done on this?

**Comment by yarikoptic** [comment]
while at it might also look at issues still assigned to Daniel and see if they need to be closed or reassigned
https://github.com/issues?q=is%3Aopen+user%3Adandi+sort%3Aupdated-asc+assignee%3Adchiquito+

**Comment by waxlamp** [comment]
I did remove Daniel from a bunch of AWS resources. AFAIK there aren't any others, but if they come up organically we can deal with case-by-case. I'll close this issue.
