### ISSUE TITLE
Finish setting up staging environment

### ISSUE THREAD

**Issue by dchiquito** [dandi/dandi-infrastructure#73]
The staging environment needs to be brought into compliance with https://github.com/dandi/dandi-api/blob/master/doc/design/staging-1.md.

- [x] `netlify.toml` needs to be tweaked so that the production deployment points to `api.dandiarchive.org`, but the staging deployment and branch deploys point at `api-staging.dandiarchive.org`. Docs are at https://docs.netlify.com/configure-builds/file-based-configuration/.

- [x] Since we still need a staging deployment, I suspect we will still need a staging branch, unless there is a way in Netlify to have a production deploy and a branch deploy from the same branch. We can keep a `staging` branch up to date with `master` using a GitHub action.

- [x] We need to make sure the CORS whitelists for the staging server allow branch previews, and that the CORS whitelists for the production server do not allow branch previews.

I think we can ignore the backend deployment requirements for right now, since we are using the `staging` branch to test publish. That should be brought up to spec as soon as publish is live.

**Comment by mvandenburgh** [comment]
> We need to make sure the CORS whitelists for the staging server allow branch previews, and that the CORS whitelists for the production server do not allow branch previews.

This is actually already set up (see Heroku config vars for `dandi-api` and `dandi-api-staging`)
