### ISSUE TITLE
how to use girder credentials system to limit access to jupyter hub/binder?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-infrastructure#9]
I see girder instance as the one to provide credential store ATM. Our alpha hub. does not require any authentication and could easily be abused. I wonder what would be our short term solution to limit access to hub and binder only to "authorized" (as authenticated with DANDI) users.
- should we deploy some dedicated credentials "service" which Girder would also use, or
- could we somehow use Girder as a credential service for the hub. etc
?

**Comment by satra** [comment]
indeed - this is the single sign on piece of yesterday's todo list.

**Comment by yarikoptic** [comment]
we have single sign on via github ATM, and no girder
