### ISSUE TITLE
Remove codepen and bioimagesuiteweb URLs from CORS whitelist

### ISSUE THREAD

**Issue by waxlamp** [dandi/dandi-infrastructure#91]
See [this comment](https://github.com/dandi/dandi-api/pull/479#discussion_r689519147) for background.

The relevant section of code to manipulate is https://github.com/dandi/dandi-infrastructure/blob/1a6c32ddee18b679b01fd9194a5ddb040bd03cd2/terraform/api.tf#L21-L27

@yarikoptic, can bioimagesuiteweb work just with read-only access to DANDI?

**Comment by yarikoptic** [comment]
> @yarikoptic, can bioimagesuiteweb work just with read-only access to DANDI?

it better does! ;) note: ATM it seems to not work anyways -- https://github.com/bioimagesuiteweb/bisweb/issues/124 (yet to be resolved)
